library(shiny)
library(shinydashboard)
library(Seurat)
library(ggplot2)
library(dplyr)
library(plotly)
library(DT)
library(viridis)
library(tidyr)
library(cancersea)
library(openxlsx)
library(corrplot)
library(slingshot)
library(SingleCellExperiment)
library(RColorBrewer)

#devtools::load_all()
#run_app()
