on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev

      - name: Install BiocManager first
        run: |
          install.packages("BiocManager")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::devtools
            local::.
          needs: website

      - name: Install Bioconductor packages
        run: |
          BiocManager::install(c("SingleCellExperiment", "slingshot"))
        shell: Rscript {0}

      - name: Install cancersea from GitHub (optional)
        run: |
          tryCatch({
            devtools::install_github("Moonerss/cancersea", quiet = TRUE, force = TRUE)
            message("cancersea installed successfully")
          }, error = function(e) {
            message("Could not install cancersea, but continuing anyway: ", e$message)
          })
        shell: Rscript {0}

      - name: Build site
        run: |
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4